export { LandingPage } from "./Landing/LandingPage";
export { CategoryPage } from "./Categories/CategoryPage";
export { QuestionPage } from "./Question/QuestionPage";
export { ProfilePage } from "./Profile/ProfilePage";
export { LeaderboardPage } from "./Leaderboard/LeaderboardPage";
export { HelpPage } from "./Help/HelpPage";
export { SettingPage } from "./Settings/SettingPage";
export { NotFound } from "./NotFound/NotFound";
export { NotificationPage } from "./Notifications/NotificationPage";
